### ISSUE TITLE
logger S3 provider: add support for sending logs to a custom S3 host (not in AWS)

### ISSUE THREAD

**Issue by OriHoch** [CloudWebManage/cwm-worker-deployment-minio#5]
probably need to add a configuration for S3_HOST and need to see that it works with our minio deployment

to test this, you will need to deploy 2 cwm-worker-deploy-minio deployments (otherwise there will be an infinite loop of logs..):

* minio deployment 1 (logs) - used as the logging destination (configured without any log provider)
* minio deployment 2 (storage) - used as the storage service (configured to send logs to S3 to the minio deployment 1)

reproduction steps:

1. login to minio deployment 2 (storage) and make some actions - create bucket, upload objects
2. login to minio deployment 1 (logs) and you should see the logs from those actions

**Comment by OriHoch** [comment]
to deploy 2 deployments you can deploy each to a separate namespace, by using the --namespace argument to the helm command

**Comment by iamAzeem** [comment]
Hi Ori,

The `s3_endpoint` configuration provides http/https endpoint setting to work with S3 compatible services.

I've been testing this scenario like this:

```shell
# logs
helm install cwm-worker-deployment-minio ./helm --namespace=logs --set minio.auditWebhookEndpoint="" --set minio.metricsLogger.enable=false

# storage
helm install cwm-worker-deployment-minio ./helm --namespace=storage --create-namespace --set minio.metricsLogger.enable=true --set minio.metricsLogger.LOG_PROVIDER=s3
```

However, there seem to be incompatibilities.

For an S3 configuration:

```text
      aws_key_id            dummykey
      aws_sec_key           dummypass
      s3_bucket             'test123'
      s3_region             us-east-1
      s3_endpoint           http://localhost:8080
```

It has been tested with and without the pre-created bucket.

But, the connection isn't successful due to the reason that it tries to connect at `test123.localhost:8080`.
Here's the error:

```text
2021-03-11 12:15:57 +0000 [error]: #0 unexpected error error_class=RuntimeError error="can't call S3 API. Please check your credentials or s3_region configuration. error = #<Errno::EADDRNOTAVAIL: Failed to open TCP connection to test123.localhost:8080 (Address not available - connect(2) for \"test123.localhost\" port 8080)>"
```

Also, the DNS http://minio.logs:8080 doesn't work.
Tried to debug that but was not successful.
This thread looks relevant but I didn't try it: https://stackoverflow.com/a/55650127/7670262.

Any pointers?

**Comment by OriHoch** [comment]
There is an example here regarding sending logs to minio -
https://docs.fluentd.org/how-to-guides/apache-to-minio
I think your configuration is missing: force_path_style true

Regarding the DNS it's a standard kubernetes feature where each service
gets an internal DNS based on the service name and the namespace
You can read more about it here -
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/

**Comment by iamAzeem** [comment]
The configuration `force_path_style true` resolved the path issue.

But, I could not get it to work with a different namespace.
I already studied that DNS thread among other relevant SO Q&A.
Also, tried with hardcoded IP addresses and with FQDN as well.
Nothing worked.
There might be some networking issues at minikube level on my machine.
If you could please test this on your side as well, that would be helpful to know the exact issue.
The PR #13 is updated for your test and review.

---

Apart from that, I tried with `logs` namespace without logger and local fluentd instance with S3 configuration.
It worked and the logs were sent over to MinIO in `.gz` format.

This was the configuration:

```text
  aws_key_id            dummykey
  aws_sec_key           dummypass
  s3_bucket             test123456
  s3_region             us-east-1
  path                  logs/
  s3_endpoint           http://localhost:8080/
  force_path_style      true
  time_slice_format     %Y%m%d%H%M
```

With port forwarding:

```shell
kubectl port-forward service/minio 8080 -n logs
```

During this testing, the `http` service crashed with these errors:

```text
E0312 17:15:09.171724  345859 portforward.go:400] an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod 0997a2a2cba0f3940230d101a5d273e34c6925aa64422af74a2ed0a87ebb0962, uid : exit status 1: 2021/03/12 12:15:09 socat[3325392] E connect(5, AF=2 127.0.0.1:8080, 16): Connection refused
```

and, `kubectl logs -f deployment/minio http -n logs`:

```text
Exiting on signal: TERMINATED
```

It came back online after a few minutes and the data was still there.
Meanwhile, the fluentd instance keeps retrying the connection and automatically connected when it was online.
Let me know if you need more information.

Here is the MinIO snapshot with data:

![minio-data](https://user-images.githubusercontent.com/7128328/110938669-1e97da00-832c-11eb-93b1-6a37f915bbec.png)

**Comment by OriHoch** [comment]
please change to support the configurations via helm values then attach the helm values you used and full reproduction steps so I can test the problem

**Comment by iamAzeem** [comment]
The helm values have been updated in #13.

Here are the steps to reproduce this:

- **logs** namespace

Install deployment:

```shell
helm install cwm-worker-deployment-minio ./helm \
  -n logs --create-namespace \
  --set minio.auditWebhookEndpoint="" \
  --set minio.metricsLogger.enable=false
```

and, forward the http port:

```shell
kubectl port-forward service/minio 8080 -n logs
```
---

- **storage** namespace

Create values file:

**.values.yaml**

```yaml
minio:
  image: minio
  tag: latest
  initDebugEnable: true
  metricsLogger:
    image: cwm-worker-logger
    tag: latest
    LOG_LEVEL: debug
    UPDATE_GRACE_PERIOD_SECONDS: 2s
    DEPLOYMENT_API_METRICS_FLUSH_INTERVAL_SECONDS: 5s
    # LOGS FLUSHING
    LOGS_FLUSH_INTERVAL: 5s
    LOGS_FLUSH_RETRY_WAIT: 10s
    LOG_PROVIDER: s3
    S3_NON_AWS_TARGET: true
    S3_ENDPOINT: http://minio.logs:8080
```

and, install deployment:

```shell
helm install cwm-worker-deployment-minio ./helm \
  -n storage --create-namespace \
  -f .values.yaml
```

**Startup errors**:

```text
kubectl logs deployment/minio logger -n storage
2021-03-13 12:24:55 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/cwm-fluent-s3.conf"
2021-03-13 12:24:55 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '4.3.3'
2021-03-13 12:24:55 +0000 [info]: gem 'fluent-plugin-http-cwm' version '0.1.0'
2021-03-13 12:24:55 +0000 [info]: gem 'fluent-plugin-s3' version '1.5.0'
2021-03-13 12:24:55 +0000 [info]: gem 'fluentd' version '1.11.5'
2021-03-13 12:24:58 +0000 [warn]: 'force_path_style' parameter is deprecated: S3 will drop path style API in 2020: See https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/
2021-03-13 12:24:58 +0000 [info]: [http_cwm_input_logs] Connecting with Redis [localhost:6379]
2021-03-13 12:24:59 +0000 [error]: [http_cwm_input_logs] Unable to connect to Redis server! ERROR: 'Error connecting to Redis on localhost:6379 (Errno::EADDRNOTAVAIL)'. Retrying...
2021-03-13 12:25:00 +0000 [error]: [http_cwm_input_logs] Unable to connect to Redis server! ERROR: 'Error connecting to Redis on localhost:6379 (Errno::EADDRNOTAVAIL)'. Retrying...
2021-03-13 12:25:01 +0000 [error]: [http_cwm_input_logs] Unable to connect to Redis server! ERROR: 'Error connecting to Redis on localhost:6379 (Errno::EADDRNOTAVAIL)'. Retrying...
2021-03-13 12:25:02 +0000 [error]: [http_cwm_input_logs] Unable to connect to Redis server! ERROR: 'Error connecting to Redis on localhost:6379 (Errno::EADDRNOTAVAIL)'. Retrying...
2021-03-13 12:25:03 +0000 [error]: [http_cwm_input_logs] Unable to connect to Redis server! ERROR: 'Error connecting to Redis on localhost:6379 (Errno::EADDRNOTAVAIL)'. Retrying...
2021-03-13 12:25:04 +0000 [error]: [http_cwm_input_logs] Unable to connect to Redis server! ERROR: 'Error connecting to Redis on localhost:6379 (Errno::EADDRNOTAVAIL)'. Retrying...
2021-03-13 12:25:05 +0000 [error]: [http_cwm_input_logs] Unable to connect to Redis server! ERROR: 'Error connecting to Redis on localhost:6379 (Errno::EADDRNOTAVAIL)'. Retrying...
2021-03-13 12:25:06 +0000 [error]: [http_cwm_input_logs] Unable to connect to Redis server! ERROR: 'Error connecting to Redis on localhost:6379 (Errno::EADDRNOTAVAIL)'. Retrying...
2021-03-13 12:25:07 +0000 [error]: [http_cwm_input_logs] Unable to connect to Redis server! ERROR: 'Error connecting to Redis on localhost:6379 (Errno::EADDRNOTAVAIL)'. Retrying...
2021-03-13 12:25:08 +0000 [debug]: No fluent logger for internal event
2021-03-13 12:25:08 +0000 [info]: using configuration file: <ROOT>
  <system>
    log_level debug
  </system>
  <source>
    @type http_cwm
    @id http_cwm_input_logs
    host "0.0.0.0"
    port 8500
    tag "logs"
    <redis>
      host "localhost"
      port 6379
      grace_period 2s
      flush_interval 5s
      last_update_prefix "deploymentid:last_action"
      metrics_prefix "deploymentid:minio-metrics"
    </redis>
  </source>
  <match logs>
    @type s3
    @id s3_log_target
    aws_key_id xxxxxx
    aws_sec_key xxxxxx
    s3_bucket "test123"
    s3_region "us-east-1"
    path "logs/"
    s3_endpoint "http://minio.logs:8080"
    force_path_style true
    ssl_verify_peer true
    time_slice_format %Y%m%d%H%M
    s3_object_key_format "%{path}%{time_slice}_%{index}.%{file_extension}"
    store_as "gzip"
    <buffer>
      @type "file"
      path "/fluentd/buf/"
      path_suffix ".buf"
      compress gzip
      flush_at_shutdown true
      flush_mode interval
      flush_interval 5s
      retry_type periodic
      retry_wait 10s
      chunk_limit_size 100m
    </buffer>
  </match>
</ROOT>
2021-03-13 12:25:08 +0000 [info]: starting fluentd-1.11.5 pid=7 ruby="2.7.2"
2021-03-13 12:25:08 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/bin/fluentd", "-c", "/fluentd/etc/cwm-fluent-s3.conf", "-p", "/fluentd/plugins", "--under-supervisor"]
2021-03-13 12:25:10 +0000 [info]: adding match pattern="logs" type="s3"
2021-03-13 12:25:15 +0000 [warn]: #0 'force_path_style' parameter is deprecated: S3 will drop path style API in 2020: See https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/
2021-03-13 12:25:15 +0000 [info]: adding source type="http_cwm"
2021-03-13 12:25:16 +0000 [info]: #0 [http_cwm_input_logs] Connecting with Redis [localhost:6379]
2021-03-13 12:25:17 +0000 [debug]: #0 No fluent logger for internal event
2021-03-13 12:25:17 +0000 [info]: #0 starting fluentd worker pid=16 ppid=7 worker=0
2021-03-13 12:25:24 +0000 [error]: #0 unexpected error error_class=RuntimeError error="can't call S3 API. Please check your credentials or s3_region configuration. error = #<Seahorse::Client::NetworkingError: Failed to open TCP connection to minio.logs:8080 (Connection refused - connect(2) for \"minio.logs\" port 8080)>"
  2021-03-13 12:25:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-s3-1.5.0/lib/fluent/plugin/out_s3.rb:469:in `rescue in check_apikeys'
  2021-03-13 12:25:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-s3-1.5.0/lib/fluent/plugin/out_s3.rb:464:in `check_apikeys'
  2021-03-13 12:25:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-s3-1.5.0/lib/fluent/plugin/out_s3.rb:254:in `start'
  2021-03-13 12:25:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.11.5/lib/fluent/root_agent.rb:200:in `block in start'
  2021-03-13 12:25:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.11.5/lib/fluent/root_agent.rb:189:in `block (2 levels) in lifecycle'
  2021-03-13 12:25:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.11.5/lib/fluent/root_agent.rb:188:in `each'
  2021-03-13 12:25:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.11.5/lib/fluent/root_agent.rb:188:in `block in lifecycle'
  2021-03-13 12:25:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.11.5/lib/fluent/root_agent.rb:175:in `each'
  2021-03-13 12:25:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.11.5/lib/fluent/root_agent.rb:175:in `lifecycle'
  2021-03-13 12:25:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.11.5/lib/fluent/root_agent.rb:199:in `start'
  2021-03-13 12:25:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.11.5/lib/fluent/engine.rb:248:in `start'
  2021-03-13 12:25:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.11.5/lib/fluent/engine.rb:147:in `run'
  2021-03-13 12:25:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.11.5/lib/fluent/supervisor.rb:607:in `block in run_worker'
  2021-03-13 12:25:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.11.5/lib/fluent/supervisor.rb:845:in `main_process'
  2021-03-13 12:25:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.11.5/lib/fluent/supervisor.rb:598:in `run_worker'
  2021-03-13 12:25:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.11.5/lib/fluent/command/fluentd.rb:361:in `<top (required)>'
  2021-03-13 12:25:24 +0000 [error]: #0 /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
  2021-03-13 12:25:24 +0000 [error]: #0 /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
  2021-03-13 12:25:24 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.11.5/bin/fluentd:8:in `<top (required)>'
  2021-03-13 12:25:24 +0000 [error]: #0 /usr/bin/fluentd:23:in `load'
  2021-03-13 12:25:24 +0000 [error]: #0 /usr/bin/fluentd:23:in `<main>'
  ...
```

---

**Testing with local fluentd instance:**

configuration with http input and s3/minio output (**fluent-minio-s3-test.conf**)

```text
<source>
  @type                 http
  bind                  0.0.0.0
  port                  8000
</source>

# S3: https://docs.fluentd.org/output/s3
<match logs>
  @type                   copy

  <store>
    @type                 stdout
  </store>

  <store>
    @type                 s3
    @id                   s3_log_target

    aws_key_id            dummykey
    aws_sec_key           dummypass
    s3_bucket             test123
    s3_region             us-east-1
    path                  logs/
    s3_endpoint           http://localhost:8080/
    force_path_style      true
    time_slice_format     %Y%m%d%H%M
    s3_object_key_format  "%{path}%{time_slice}_%{index}.%{file_extension}"
    store_as              "txt"

    <buffer>
      @type               "file"
      path                "~/Downlaods/buffer.*.*"
      path_suffix         ".buf"
      compress            gzip
      flush_at_shutdown   true
      flush_mode          interval
      flush_interval      5s
      retry_type          periodic
      retry_wait          10s
      chunk_limit_size    100m
    </buffer>
  </store>
</match>
```

Run fluentd with this configuration:

```shell
fluentd -c ./fluent-minio-s3-test.conf -v
```

Send test logs via `curl`:

```shell
curl -X POST -d 'json={"foo":"bar"}' http://localhost:8000/logs
```

fluentd `stdout` and `s3` logs:

```text
2021-03-13 18:03:53.069563102 +0500 logs: {"foo":"bar"}
2021-03-13 18:03:53 +0500 [debug]: #0 [s3_log_target] Created new chunk chunk_id="5bd6aa604d257af41ad4b6cf0cf457c7" metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=1615575600, tag=nil, variables=nil, seq=0>
2021-03-13 18:03:59 +0500 [debug]: #0 [s3_log_target] out_s3: write chunk 5bd6aa604d257af41ad4b6cf0cf457c7 with metadata #<struct Fluent::Plugin::Buffer::Metadata timekey=1615575600, tag=nil, variables=nil, seq=0> to s3://test123/logs/202103130000_0.txt
```

Screenshot with downloaded content file:

![minio-test-screenshot](https://user-images.githubusercontent.com/7128328/111030856-4cf9e000-8426-11eb-97a3-6164ffa753b1.png)

**Comment by OriHoch** [comment]
looks like it was due to short time of probes which kept failing and restaring the containers
fixed in this commit - https://github.com/CloudWebManage/cwm-worker-deployment-minio/pull/13/commits/b068b07bcb8f0215967f6d09beb3773b12eb3441
I tested and it works, merged the PR

**Comment by iamAzeem** [comment]
Right. Thanks for the explanation!
I believe other related issues, #8 and #9, can also be closed with this PR.

**Comment by iamAzeem** [comment]
Just tested on my side. Worked seamlessly!
